# Netflix Movie Data Analysis

This project explores a movie dataset using Python, Pandas, Matplotlib, and Seaborn.  
The analysis focuses on genres, vote categories, popularity, and release-year trends.

## Project questions

1. Which genres appear most frequently?
2. Which vote category has the highest number of movies?
3. Which movies are the most and least popular?
4. Which years had the highest number of movie releases?
5. Is there any relationship between popularity, vote count, and vote average?

## Phase-1: Importing Modules and Data Loading

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("mymoviedb.csv", lineterminator='\n')
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

## Phase 2 — Initial data inspection

In [3]:
print("Shape:",df.shape)
df.info()

Shape: (9827, 9)
<class 'pandas.DataFrame'>
RangeIndex: 9827 entries, 0 to 9826
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   str
 1   Title              9827 non-null   str
 2   Overview           9827 non-null   str
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   int64
 5   Vote_Average       9827 non-null   float64
 6   Original_Language  9827 non-null   str
 7   Genre              9827 non-null   str
 8   Poster_Url         9827 non-null   str
dtypes: float64(2), int64(1), str(6)
memory usage: 691.1 KB

In [4]:
df['Genre'].head() # in order to find the types of genre being used in the dataset

0    Action, Adventure, Science Fiction
1              Crime, Mystery, Thriller
2                              Thriller
3    Animation, Comedy, Family, Fantasy
4      Action, Adventure, Thriller, War
Name: Genre, dtype: str

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
print(df.describe())

        Popularity    Vote_Count  Vote_Average
count  9827.000000   9827.000000   9827.000000
mean     40.326088   1392.805536      6.439534
std     108.873998   2611.206907      1.129759
min      13.354000      0.000000      0.000000
25%      16.128500    146.000000      5.900000
50%      21.199000    444.000000      6.500000
75%      35.191500   1376.000000      7.100000
max    5083.954000  31077.000000     10.000000

In [7]:
# Release-Date datatype/format needs to be changed
# white spaces between the Genre types may or may not needed to be removed
# dropping down the columns that needs not analysis(like-overview, language and poster url)
# All of these things needs to be done in the data preprocessing.
# Insights gained till now-

### Exploratory summary
- we have a dataframe consisting of 9827 entries and 9 columns.
- our dataset looks a bit tidy with no NaNs or duplicated values.
- Release_Date column need to be casted into date time and to extract only the year value.
- Overview, Original_Language and Poster-Url wouldn't be so useful during analysis, so we'll drop them.
- There is noticable outliers in the Popularity column.
- Vote_Average better be categorised for proper analysis.
- Genre column has comma separated values and white spaces that needs to be handled and casted into category.

### Phase-3: Cleaning Data and Preprocessing

In [8]:
# changing the date time format of the Release_Date column

df['Release_Date'] = pd.to_datetime(df['Release_Date'])
print(df['Release_Date'].dtypes)

df['Release_Date'] = df['Release_Date'].dt.year
df['Release_Date'].dtypes

datetime64[us]

dtype('int32')

In [9]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

#### Dropping down the irrelevant columns

In [10]:
# Overview, Original_Language, Poster_Url column to be dropped

cols = ['Overview', 'Original_Language', 'Poster_Url']
df.drop(cols, axis = 1, inplace = True)
df.columns

Index(['Release_Date', 'Title', 'Popularity', 'Vote_Count', 'Vote_Average',
       'Genre'],
      dtype='str')

In [11]:
df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122,6.3,Thriller
3,2021,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War"

#### **Categorizing** `Vote_Average` column  
We would cut the `Vote_Average` values and make 4 categories `popular`,`average`, `below_avg` , `not_popular` to describe it more using categorize_col() function provided

In [12]:
# creating a user defined function to label the popularity of the movie

def categorize_col(df, col, labels):
    
    edges = [df[col].describe()['min'],
             df[col].describe()['25%'],
             df[col].describe()['50%'],
             df[col].describe()['75%'],
             df[col].describe()['max']]
    df[col] = pd.cut(df[col], edges, labels = labels, duplicates = 'drop')
    return df

In [13]:
labels = ['not_popular', 'below_avg', 'average', 'popular']

categorize_col(df, 'Vote_Average', labels)

df['Vote_Average'].unique()

['popular', 'below_avg', 'average', 'not_popular', NaN]
Categories (4, str): ['not_popular' < 'below_avg' < 'average' < 'popular']

In [14]:
df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,popular,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,popular,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122,below_avg,Thriller
3,2021,Encanto,2402.201,5076,popular,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793,average,"Action, Adventure, Thriller, War"

In [15]:
df['Vote_Average'].value_counts()

Vote_Average
not_popular    2467
popular        2450
average        2412
below_avg      2398
Name: count, dtype: int64

In [16]:
df.dropna(inplace=True)
df.isna().sum()

Release_Date    0
Title           0
Popularity      0
Vote_Count      0
Vote_Average    0
Genre           0
dtype: int64

In [17]:
df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,popular,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,popular,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122,below_avg,Thriller
3,2021,Encanto,2402.201,5076,popular,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793,average,"Action, Adventure, Thriller, War"

# Phase 4 — Linear Regression Model

In [18]:
df_ml = df.copy()
df_ml.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,popular,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,popular,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122,below_avg,Thriller
3,2021,Encanto,2402.201,5076,popular,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793,average,"Action, Adventure, Thriller, War"

In [19]:
df_ml.info()

<class 'pandas.DataFrame'>
Index: 9727 entries, 0 to 9826
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Release_Date  9727 non-null   int32
 1   Title         9727 non-null   str
 2   Popularity    9727 non-null   float64
 3   Vote_Count    9727 non-null   int64
 4   Vote_Average  9727 non-null   category
 5   Genre         9727 non-null   str
dtypes: category(1), float64(1), int32(1), int64(1), str(2)
memory usage: 427.7 KB

## Feature Selection

In [20]:
# Removing unnecessary columns

df_ml = df_ml.drop(columns=['Title'])

df_ml.head()

,Release_Date,Popularity,Vote_Count,Vote_Average,Genre
0,2021,5083.954,8940,popular,"Action, Adventure, Science Fiction"
1,2022,3827.658,1151,popular,"Crime, Mystery, Thriller"
2,2022,2618.087,122,below_avg,Thriller
3,2021,2402.201,5076,popular,"Animation, Comedy, Family, Fantasy"
4,2021,1895.511,1793,average,"Action, Adventure, Thriller, War"

In [21]:
## Checking Data Types
df_ml.dtypes

Release_Date       int32
Popularity       float64
Vote_Count         int64
Vote_Average    category
Genre                str
dtype: object

In [22]:
## Encoding Vote Average
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df_ml['Vote_Average'] = le.fit_transform(df_ml['Vote_Average'])
df_ml.head()

,Release_Date,Popularity,Vote_Count,Vote_Average,Genre
0,2021,5083.954,8940,3,"Action, Adventure, Science Fiction"
1,2022,3827.658,1151,3,"Crime, Mystery, Thriller"
2,2022,2618.087,122,1,Thriller
3,2021,2402.201,5076,3,"Animation, Comedy, Family, Fantasy"
4,2021,1895.511,1793,0,"Action, Adventure, Thriller, War"

In [24]:
print(le.classes_)

['average' 'below_avg' 'not_popular' 'popular']

## Final Feature Selection

In [28]:
# Removing Genre column for the first model

df_ml = df_ml.drop(columns = ['Genre'])

df_ml.head()

   Release_Date  Popularity  Vote_Count  Vote_Average
0          2021    5083.954        8940             3
1          2022    3827.658        1151             3
2          2022    2618.087         122             1
3          2021    2402.201        5076             3
4          2021    1895.511        1793             0

# Phase 5 - Splitting Features and Targets

In [30]:
# Features (Independent Variables)
X = df_ml.drop(columns=['Popularity'])

# Target (Dependent Variable)
y = df_ml['Popularity']

print("Features:")
display(X.head())

print('\nTarget:')
display(y.head())

Features:

   Release_Date  Vote_Count  Vote_Average
0          2021        8940             3
1          2022        1151             3
2          2022         122             1
3          2021        5076             3
4          2021        1793             0

Target:

0    5083.954
1    3827.658
2    2618.087
3    2402.201
4    1895.511
Name: Popularity, dtype: float64

In [31]:
print('Shape of X :', X.shape)
print('Shape of y:', y.shape)

Shape of X : (9727, 3)
Shape of y: (9727,)

# Phase 6 — Train Test Split

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

In [36]:
print('Training Features :', X_train.shape)
print('Testing Features :', X_test.shape)

print()

print('Training Target :', y_train.shape)
print('Testing Target :', y_test.shape)

print("Model trained successfully!")
print(model)

Training Features : (7781, 3)
Testing Features : (1946, 3)

Training Target : (7781,)
Testing Target : (1946,)
Model trained successfully!
LinearRegression()

# Phase 7 — Training the Linear Regression Model

In [37]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

# Phase 8 — Making Predictions

In [38]:
# Predicting popularity using test data

y_pred = model.predict(X_test)

print("First 10 predictions:\n")
print(y_pred[:10])

First 10 predictions:

[37.75332888 40.45607672 43.56751553 27.58971875 57.89738518 46.16981961
 -6.3236441  44.34189135 28.82495137 36.85687102]

In [41]:
prediction_df = X_test.copy()

prediction_df['Actual_Popularity'] = y_test
prediction_df['Predicted_Popularity'] = y_pred

prediction_df = prediction_df.round(2)
prediction_df.head(10)

,Release_Date,Vote_Count,Vote_Average,Actual_Popularity,Predicted_Popularity
1159,2008,840,2,59.45,37.75
4389,2004,1997,2,23.00,40.46
5722,2000,3152,3,19.10,43.57
1625,1979,3319,3,47.54,27.59
3496,2015,3768,1,26.96,57.90
120,2022,455,0,246.65,46.17
5700,1958,220,0,19.16,-6.32
1473,2021,254,0,51.10,44.34
7701,1996,1139,0,15.67,28.82
3207,2000,2002,1,28.77,36.86

# Phase 9 — Model Evaluation

In [42]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [43]:
mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

In [44]:
print(f"Mean Absolute Error: {mae:.2f}")
print(f"Mean Squared Error: {mse:.2f}")
print(f"Root Mean Squared Error: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")

Mean Absolute Error: 33.50
Mean Squared Error: 24984.54
Root Mean Squared Error: 158.06
R2 Score: 0.03